openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in HTML.
  version: 0.1.9
servers:
  - url: https://c37jie789e.execute-api.us-west-2.amazonaws.com/dev
    description: localhost server
tags:
  - name: SignUp[Auth]
    description: Auth APIs[SignUp]
  - name: LogIn[Auth]
    description: Auth APIs[LogIn]
  - name: GetUser[Auth]
    description: Auth APIs
paths:
  /auth/signup:
    post:
      tags:
        - SignUp[Auth]
      summary: Create a user.
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User[Signup]'
      responses:
        '200':
          description: A user created.
        '500':
          description: One of the parameters is wrong. Please correct it.

  /auth/login:
    post:
      tags:
        - LogIn[Auth]
      summary: Log in a user.
      description: Optional extended description in CommonMark or HTML.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User[Login]'
      responses:
        '200':
          description: Successful login.
        '500':
          description: One of the parameters is wrong. Please correct it.

  /user:
    get:
      tags:
        - GetUser[Auth]
      summary: Get user Details.
      description: Optional extended description in CommonMark or HTML.
      security:
        - apiKeyAuth: []
      responses:
        '200':
          description: 'Successful Fetched User Details'
        '500':
          description: 'ERROR'
 
  /user/forgotpassword:
   post:
    tags:
     - GetUser[Auth]
    summary: Forget password confirmation code.
    description: Optional extended description in CommonMark or HTML.
    requestBody:
     content:
      application/json:
       schema:
        $ref: '#/components/schemas/User[forgetpassword]'
    responses:
     '200':
       description: 'Successful Fetched User Details'
     '500':
       description: 'ERROR'
  /user/updatepassword:
   post:
    tags:
     - GetUser[Auth]
    summary: Forget password confirmation code.
    description: Optional extended description in CommonMark or HTML.
    requestBody:
     content:
      application/json:
       schema:
        $ref: '#/components/schemas/User[updatepassword]'
    responses:
     '200':
       description: 'Successful Fetched User Details'
     '500':
       description: 'ERROR'       
     

      
     


    





components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
  schemas:
    User[Signup]:
      type: object
      properties:
        email:
          type: string
          example: "test1@yopmail.com"
          required: true
        password:
          type: string
          example: "test12345"
          required: true
        phone_no:
          type: string
          example: "1234569870"
          required: true
    User[Login]:
      type: object
      properties:
        email:
          type: string
          example: "test1@yopmail.com"
          required: true
        password:
          type: string
          example: "test12345"
          required: true
    User[forgetpassword]:
     type: object
     properties:
      Username:
       type: string
       example: "test1@yopmail.com"
       required: true
    User[updatepassword]:
     type: object
     properties:
      Username:
       type: string
       example: "test1@yopmail.com"
       required: true
      Password:
       type: string
       example: "test123456"
       required: true
      ConfirmationCode:
       type: integer
       example: "035121"
       required: true
       

        

          
